export const SERVER_ADD_WINDOW = 'SERVER_ADD_WINDOW';
export const SERVER_UPDATE_WINDOW = 'SERVER_UPDATE_WINDOW';
export const SERVER_DELETE_WINDOW = 'SERVER_DELETE_WINDOW';
export const SERVER_UPDATE_MEMBERS = 'SERVER_UPDATE_MEMBERS';
export const SERVER_DELETE_MEMBERS = 'SERVER_DELETE_MEMBERS';
