export const ADD_WINDOW_SERVER = 'ADD_WINDOW_SERVER';
export const UPDATE_WINDOW_SERVER = 'UPDATE_WINDOW_SERVER';
export const DELETE_WINDOW_SERVER = 'DELETE_WINDOW_SERVER';
export const ADD_MEMBERS_SERVER = 'ADD_MEMBERS_SERVER';
export const DELETE_MEMBERS_SERVER = 'DELETE_MEMBERS_SERVER';
