export const ADD_WINDOW = 'ADD_WINDOW';
export const UPDATE_WINDOW = 'UPDATE_WINDOW';
export const DELETE_WINDOW = 'DELETE_WINDOW';
export const UPDATE_MEMBERS = 'UPDATE_MEMBERS';
export const DELETE_MEMBERS = 'DELETE_MEMBERS';
export const SEND_MESSAGE = 'SEND_MESSAGE';
