#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

set -e

mkdir -p $ROOT/tmp-install-qooxdoo
mkdir -p $ROOT/vendor

cd $ROOT/tmp-install-qooxdoo

wget http://downloads.sourceforge.net/qooxdoo/qooxdoo-3.5-sdk.zip
unzip qooxdoo-3.5-sdk.zip

mv qooxdoo-3.5-sdk $ROOT/vendor/qooxdoo-sdk

rm -fr $ROOT/tmp-install-qooxdoo
